name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run check-types

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
